### ISSUE TITLE
Cannot read property 'listAssets' of undefined

### ISSUE THREAD

**Issue by DorianGrey** [flaviait/ng2-jspm-template#26]
The error above sometimes occurs when triggering rebuilds. I'm not sure if this is a problem that may be caused by usage of JSPM + SystemJs plugins or because of an error within these.
We should try to figure out how to trigger this reliably, and maybe create an issue once we're sure it's not our mistake.

```
err  TypeError: Cannot read property 'listAssets' of undefined
    at /home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/lib/compile.js:213:21
    at Array.map (native)
    at pluginBundleHook (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/lib/compile.js:209:47)
    at /home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/lib/compile.js:354:12
    at tryCatcher (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:630:18)
    at PromiseArray._resolve (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:566:26)
    at Promise._settlePromise0 (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/home/linne/Projects/ng2-jspm-template/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:17
```

**Comment by sv2dev** [comment]
Yes, I saw this error before, too. But I cannot tell the steps to reproduce. It happens once in a while.
